services:

  postgres:
    image: postgres:16.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@postgres
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgres-data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - 18080:8080
  
  pgadmin:
    image: dpage/pgadmin4:8.8
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "18888:80"
    volumes:
      - ${PWD}/pgadmin-data:/var/lib/pgadmin


