services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 18080:8080

  postgres:
    image: postgres:16.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pg123456
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgres-data:/var/lib/postgresql/data
